// Package contacts provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package contacts

// GetContactsParams defines parameters for GetContacts.
type GetContactsParams struct {
	// Q search query parameter
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Page page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Pagination pagination style
	Pagination *string `form:"pagination,omitempty" json:"pagination,omitempty"`
}

// ValidateEmailParams defines parameters for ValidateEmail.
type ValidateEmailParams struct {
	// Email email to validate
	Email string `form:"email" json:"email"`
}
